package thaumicenergistics.fml;

import com.google.common.eventbus.EventBus;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;

@SuppressWarnings("UnstableApiUsage")
public class ThaumicCoreModContainer extends DummyModContainer {

    public ThaumicCoreModContainer() {
        super(new ModMetadata());
        final ModMetadata metadata = this.getMetadata();
        metadata.autogenerated = false;
        metadata.authorList.add("Nividica");
        metadata.credits = "Nividica";
        metadata.modId = "ThE-core";
        metadata.version = "1.0.0.1";
        metadata.name = "Thaumic Energistics Core";
        metadata.url = "http://minecraft.curseforge.com/projects/thaumic-energistics";
        metadata.logoFile = "assets/thaumicenergistics/meta/logo.png";
        metadata.description = "Embedded Coremod for Thaumic Energistics";
        metadata.parent = "thaumicenergistics";
    }

    @Override
    public boolean registerBus(final EventBus bus, final LoadController controller) {
        return true;
    }
}
